// <auto-generated />
using System;
using GuildManager_DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuildManagerDataAccess.Migrations
{
    [DbContext(typeof(GuildManagerDbContext))]
    [Migration("20230124094836_raidsseederx")]
    partial class raidsseederx
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuildManager_DataAccess.Entities.Character", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("int");

                    b.Property<int>("ClassSpecializationId")
                        .HasColumnType("int");

                    b.Property<decimal>("ItemLevel")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClassId");

                    b.HasIndex("ClassSpecializationId");

                    b.HasIndex("UserId");

                    b.ToTable("Characters");
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.CharacterClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CharacterClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "deathknight.png",
                            Name = "Death knight"
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "demonhunter.jpg",
                            Name = "Demon hunter"
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "druid.png",
                            Name = "Druid"
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "evoker.jpg",
                            Name = "Evoker"
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "hunter.png",
                            Name = "Hunter"
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "mage.png",
                            Name = "Mage"
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "monk.png",
                            Name = "Monk"
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "paladin.png",
                            Name = "Paladin"
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "priest.png",
                            Name = "Priest"
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "rogue.png",
                            Name = "Rogue"
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "shaman.png",
                            Name = "Shaman"
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "warlock.png",
                            Name = "Warlock"
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "warrior.png",
                            Name = "warrior"
                        });
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.ClassSpecialization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CharacterClassId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CharacterClassId");

                    b.ToTable("ClassSpecializations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CharacterClassId = 1,
                            ImageUrl = "deathknight/blood.png",
                            Name = "Blood",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            CharacterClassId = 1,
                            ImageUrl = "deathknight/frost.png",
                            Name = "Frost",
                            Role = 3
                        },
                        new
                        {
                            Id = 3,
                            CharacterClassId = 1,
                            ImageUrl = "deathknight/unholy.png",
                            Name = "Unholy",
                            Role = 3
                        },
                        new
                        {
                            Id = 4,
                            CharacterClassId = 2,
                            ImageUrl = "demonhunter/havoc.jpg",
                            Name = "Havoc",
                            Role = 3
                        },
                        new
                        {
                            Id = 5,
                            CharacterClassId = 2,
                            ImageUrl = "demonhunter/vengeance.jpg",
                            Name = "Vengeance",
                            Role = 0
                        },
                        new
                        {
                            Id = 6,
                            CharacterClassId = 3,
                            ImageUrl = "druid/balance.png",
                            Name = "Balance",
                            Role = 2
                        },
                        new
                        {
                            Id = 7,
                            CharacterClassId = 3,
                            ImageUrl = "druid/feral.png",
                            Name = "Feral",
                            Role = 3
                        },
                        new
                        {
                            Id = 8,
                            CharacterClassId = 3,
                            ImageUrl = "druid/guardian.png",
                            Name = "Guardian",
                            Role = 0
                        },
                        new
                        {
                            Id = 9,
                            CharacterClassId = 3,
                            ImageUrl = "druid/restoration.png",
                            Name = "Restoration",
                            Role = 1
                        },
                        new
                        {
                            Id = 10,
                            CharacterClassId = 4,
                            ImageUrl = "evoker/devastation.jpg",
                            Name = "Devastation",
                            Role = 2
                        },
                        new
                        {
                            Id = 11,
                            CharacterClassId = 4,
                            ImageUrl = "evoker/preservation.jpg",
                            Name = "Preservation",
                            Role = 1
                        },
                        new
                        {
                            Id = 12,
                            CharacterClassId = 5,
                            ImageUrl = "hunter/beastmastery.png",
                            Name = "Beast Mastery",
                            Role = 2
                        },
                        new
                        {
                            Id = 13,
                            CharacterClassId = 5,
                            ImageUrl = "hunter/marksmanship.png",
                            Name = "Marksmanship",
                            Role = 2
                        },
                        new
                        {
                            Id = 14,
                            CharacterClassId = 5,
                            ImageUrl = "hunter/survival.png",
                            Name = "Survival",
                            Role = 3
                        },
                        new
                        {
                            Id = 15,
                            CharacterClassId = 6,
                            ImageUrl = "mage/arcane.png",
                            Name = "Arcane",
                            Role = 2
                        },
                        new
                        {
                            Id = 16,
                            CharacterClassId = 6,
                            ImageUrl = "mage/fire.png",
                            Name = "Fire",
                            Role = 2
                        },
                        new
                        {
                            Id = 17,
                            CharacterClassId = 6,
                            ImageUrl = "mage/frost.png",
                            Name = "Frost",
                            Role = 2
                        },
                        new
                        {
                            Id = 18,
                            CharacterClassId = 7,
                            ImageUrl = "monk/brewmaster.png",
                            Name = "Brewmaster",
                            Role = 0
                        },
                        new
                        {
                            Id = 19,
                            CharacterClassId = 7,
                            ImageUrl = "monk/mistweaver.png",
                            Name = "Mistweaver",
                            Role = 1
                        },
                        new
                        {
                            Id = 20,
                            CharacterClassId = 7,
                            ImageUrl = "monk/windwalker.png",
                            Name = "Windwalker",
                            Role = 3
                        },
                        new
                        {
                            Id = 21,
                            CharacterClassId = 8,
                            ImageUrl = "paladin/holy.png",
                            Name = "Holy",
                            Role = 1
                        },
                        new
                        {
                            Id = 22,
                            CharacterClassId = 8,
                            ImageUrl = "paladin/protection.png",
                            Name = "Protection",
                            Role = 0
                        },
                        new
                        {
                            Id = 23,
                            CharacterClassId = 8,
                            ImageUrl = "paladin/retribution.png",
                            Name = "Retribution",
                            Role = 3
                        },
                        new
                        {
                            Id = 24,
                            CharacterClassId = 9,
                            ImageUrl = "priest/discipline.png",
                            Name = "Discipline",
                            Role = 1
                        },
                        new
                        {
                            Id = 25,
                            CharacterClassId = 9,
                            ImageUrl = "priest/holy.png",
                            Name = "Holy",
                            Role = 1
                        },
                        new
                        {
                            Id = 26,
                            CharacterClassId = 9,
                            ImageUrl = "priest/shadow.png",
                            Name = "Shadow",
                            Role = 2
                        },
                        new
                        {
                            Id = 27,
                            CharacterClassId = 10,
                            ImageUrl = "rogue/assassination.png",
                            Name = "Assassination",
                            Role = 3
                        },
                        new
                        {
                            Id = 28,
                            CharacterClassId = 10,
                            ImageUrl = "rogue/combat.png",
                            Name = "Outlaw",
                            Role = 3
                        },
                        new
                        {
                            Id = 29,
                            CharacterClassId = 10,
                            ImageUrl = "rogue/subtlety.png",
                            Name = "Subtlety",
                            Role = 3
                        },
                        new
                        {
                            Id = 30,
                            CharacterClassId = 11,
                            ImageUrl = "shaman/elemental.png",
                            Name = "Elemental",
                            Role = 2
                        },
                        new
                        {
                            Id = 31,
                            CharacterClassId = 11,
                            ImageUrl = "shaman/enhancement.png",
                            Name = "Enhancement",
                            Role = 3
                        },
                        new
                        {
                            Id = 32,
                            CharacterClassId = 11,
                            ImageUrl = "shaman/restoration.png",
                            Name = "Restoration",
                            Role = 1
                        },
                        new
                        {
                            Id = 33,
                            CharacterClassId = 12,
                            ImageUrl = "warlock/affliction.png",
                            Name = "Affliction",
                            Role = 2
                        },
                        new
                        {
                            Id = 34,
                            CharacterClassId = 12,
                            ImageUrl = "warlock/demonology.png",
                            Name = "Demonology",
                            Role = 2
                        },
                        new
                        {
                            Id = 35,
                            CharacterClassId = 12,
                            ImageUrl = "warlock/destruction.png",
                            Name = "Destruction",
                            Role = 2
                        },
                        new
                        {
                            Id = 36,
                            CharacterClassId = 13,
                            ImageUrl = "warrior/arms.png",
                            Name = "Arms",
                            Role = 3
                        },
                        new
                        {
                            Id = 37,
                            CharacterClassId = 13,
                            ImageUrl = "warrior/fury.png",
                            Name = "Fury",
                            Role = 3
                        },
                        new
                        {
                            Id = 38,
                            CharacterClassId = 13,
                            ImageUrl = "warrior/protection.png",
                            Name = "Protection",
                            Role = 0
                        });
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.Raids.RaidEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoAccept")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RaidLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RaidLocationId");

                    b.ToTable("RaidEvents");
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.Raids.RaidEventCharacter", b =>
                {
                    b.Property<int>("CharacterId")
                        .HasColumnType("int");

                    b.Property<int>("RaidEventId")
                        .HasColumnType("int");

                    b.Property<int>("AcceptanceStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(2);

                    b.HasKey("CharacterId", "RaidEventId");

                    b.HasIndex("RaidEventId");

                    b.ToTable("RaidEventCharacter");
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.Raids.RaidExpansion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RaidExpansions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "",
                            Name = "World of Warcraft Classic"
                        },
                        new
                        {
                            Id = 2,
                            Name = "The Burning Crusade"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Wrath of the Lich King"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Cataclysm"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Mists of Pandaria"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Warlords of Draenor"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Legion"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Battle for Azeroth"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Shadowlands"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Dragonflight"
                        });
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.Raids.RaidLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RaidDifficulty")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("RaidExpansionId")
                        .HasColumnType("int");

                    b.Property<int?>("RaidExpansionId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaidExpansionId");

                    b.HasIndex("RaidExpansionId1");

                    b.ToTable("RaidLocations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ImageUrl = "raids/1.png",
                            Name = "Blackwing Lair",
                            RaidDifficulty = 0,
                            RaidExpansionId = 1
                        },
                        new
                        {
                            Id = 2,
                            ImageUrl = "raids/2.png",
                            Name = "Molten Core",
                            RaidDifficulty = 0,
                            RaidExpansionId = 1
                        },
                        new
                        {
                            Id = 3,
                            ImageUrl = "raids/3.png",
                            Name = "Onyxia's Lair",
                            RaidDifficulty = 0,
                            RaidExpansionId = 1
                        },
                        new
                        {
                            Id = 4,
                            ImageUrl = "raids/4.png",
                            Name = "Zul'Gurub",
                            RaidDifficulty = 0,
                            RaidExpansionId = 1
                        },
                        new
                        {
                            Id = 5,
                            ImageUrl = "raids/5.png",
                            Name = "Aq40",
                            RaidDifficulty = 0,
                            RaidExpansionId = 1
                        },
                        new
                        {
                            Id = 6,
                            ImageUrl = "raids/6.png",
                            Name = "Karazhan",
                            RaidDifficulty = 0,
                            RaidExpansionId = 2
                        },
                        new
                        {
                            Id = 7,
                            ImageUrl = "raids/7.png",
                            Name = "Gruul's Lair",
                            RaidDifficulty = 0,
                            RaidExpansionId = 2
                        },
                        new
                        {
                            Id = 8,
                            ImageUrl = "raids/8.png",
                            Name = "Magtheridon's Lair",
                            RaidDifficulty = 0,
                            RaidExpansionId = 2
                        },
                        new
                        {
                            Id = 9,
                            ImageUrl = "raids/9.png",
                            Name = "Serpentshrine Cavern",
                            RaidDifficulty = 0,
                            RaidExpansionId = 2
                        },
                        new
                        {
                            Id = 10,
                            ImageUrl = "raids/10.png",
                            Name = "Tempest Keep: The Eye",
                            RaidDifficulty = 0,
                            RaidExpansionId = 2
                        },
                        new
                        {
                            Id = 11,
                            ImageUrl = "raids/11.png",
                            Name = "Black Temple",
                            RaidDifficulty = 0,
                            RaidExpansionId = 2
                        },
                        new
                        {
                            Id = 12,
                            ImageUrl = "raids/12.png",
                            Name = "Hyjal Summit",
                            RaidDifficulty = 0,
                            RaidExpansionId = 2
                        },
                        new
                        {
                            Id = 13,
                            ImageUrl = "raids/13.png",
                            Name = "Sunwell Plateau",
                            RaidDifficulty = 0,
                            RaidExpansionId = 2
                        },
                        new
                        {
                            Id = 14,
                            ImageUrl = "raids/14.png",
                            Name = "Naxxramas",
                            RaidDifficulty = 0,
                            RaidExpansionId = 3
                        },
                        new
                        {
                            Id = 15,
                            ImageUrl = "raids/15.png",
                            Name = "Ulduar",
                            RaidDifficulty = 0,
                            RaidExpansionId = 3
                        },
                        new
                        {
                            Id = 16,
                            ImageUrl = "raids/16.png",
                            Name = "Trial of the Crusader",
                            RaidDifficulty = 0,
                            RaidExpansionId = 3
                        },
                        new
                        {
                            Id = 17,
                            ImageUrl = "raids/17.png",
                            Name = "Icecrown Citadel",
                            RaidDifficulty = 0,
                            RaidExpansionId = 3
                        },
                        new
                        {
                            Id = 18,
                            ImageUrl = "raids/18.png",
                            Name = "Firelands",
                            RaidDifficulty = 0,
                            RaidExpansionId = 4
                        },
                        new
                        {
                            Id = 19,
                            ImageUrl = "raids/19.png",
                            Name = "Dragon Soul",
                            RaidDifficulty = 0,
                            RaidExpansionId = 4
                        },
                        new
                        {
                            Id = 20,
                            ImageUrl = "raids/20.png",
                            Name = "Baradin Hold",
                            RaidDifficulty = 0,
                            RaidExpansionId = 4
                        },
                        new
                        {
                            Id = 21,
                            ImageUrl = "raids/21.png",
                            Name = "Blackwing Descent",
                            RaidDifficulty = 0,
                            RaidExpansionId = 4
                        },
                        new
                        {
                            Id = 22,
                            ImageUrl = "raids/22.png",
                            Name = "Throne of the Four Winds",
                            RaidDifficulty = 0,
                            RaidExpansionId = 4
                        },
                        new
                        {
                            Id = 23,
                            ImageUrl = "raids/23.png",
                            Name = "Mogu'shan Vaults",
                            RaidDifficulty = 0,
                            RaidExpansionId = 5
                        },
                        new
                        {
                            Id = 24,
                            ImageUrl = "raids/24.png",
                            Name = "Heart of Fear",
                            RaidDifficulty = 0,
                            RaidExpansionId = 5
                        },
                        new
                        {
                            Id = 25,
                            ImageUrl = "raids/25.png",
                            Name = "Terrace of Endless Spring",
                            RaidDifficulty = 0,
                            RaidExpansionId = 5
                        },
                        new
                        {
                            Id = 26,
                            ImageUrl = "raids/26.png",
                            Name = "Highmaul",
                            RaidDifficulty = 0,
                            RaidExpansionId = 6
                        },
                        new
                        {
                            Id = 27,
                            ImageUrl = "raids/27.png",
                            Name = "Blackrock Foundry",
                            RaidDifficulty = 0,
                            RaidExpansionId = 6
                        },
                        new
                        {
                            Id = 28,
                            ImageUrl = "raids/28.png",
                            Name = "Hellfire Citadel",
                            RaidDifficulty = 0,
                            RaidExpansionId = 6
                        },
                        new
                        {
                            Id = 29,
                            ImageUrl = "raids/29.png",
                            Name = "The Emerald Nightmare",
                            RaidDifficulty = 0,
                            RaidExpansionId = 7
                        },
                        new
                        {
                            Id = 30,
                            ImageUrl = "raids/30.png",
                            Name = "Trial of Valor",
                            RaidDifficulty = 0,
                            RaidExpansionId = 7
                        },
                        new
                        {
                            Id = 31,
                            ImageUrl = "raids/31.png",
                            Name = "The Nighthold",
                            RaidDifficulty = 0,
                            RaidExpansionId = 7
                        },
                        new
                        {
                            Id = 32,
                            ImageUrl = "raids/32.png",
                            Name = "Tomb of Sargeras",
                            RaidDifficulty = 0,
                            RaidExpansionId = 7
                        },
                        new
                        {
                            Id = 33,
                            ImageUrl = "raids/33.png",
                            Name = "Antorus, the Burning Throne",
                            RaidDifficulty = 0,
                            RaidExpansionId = 7
                        },
                        new
                        {
                            Id = 34,
                            ImageUrl = "raids/34.png",
                            Name = "Uldir",
                            RaidDifficulty = 0,
                            RaidExpansionId = 8
                        },
                        new
                        {
                            Id = 35,
                            ImageUrl = "raids/35.png",
                            Name = "Battle of Dazar'alor",
                            RaidDifficulty = 0,
                            RaidExpansionId = 8
                        },
                        new
                        {
                            Id = 36,
                            ImageUrl = "raids/36.png",
                            Name = "Crucible of Storms",
                            RaidDifficulty = 0,
                            RaidExpansionId = 8
                        },
                        new
                        {
                            Id = 37,
                            ImageUrl = "raids/37.png",
                            Name = "The Eternal Palace",
                            RaidDifficulty = 0,
                            RaidExpansionId = 8
                        },
                        new
                        {
                            Id = 38,
                            ImageUrl = "raids/38.png",
                            Name = "Ny'alotha, the Waking City",
                            RaidDifficulty = 0,
                            RaidExpansionId = 8
                        },
                        new
                        {
                            Id = 39,
                            ImageUrl = "raids/39.png",
                            Name = "Castle Nathria",
                            RaidDifficulty = 0,
                            RaidExpansionId = 9
                        },
                        new
                        {
                            Id = 40,
                            ImageUrl = "raids/40.png",
                            Name = "Sanctum of Domination",
                            RaidDifficulty = 0,
                            RaidExpansionId = 9
                        },
                        new
                        {
                            Id = 41,
                            ImageUrl = "raids/41.png",
                            Name = "Sepulcher of the First Ones",
                            RaidDifficulty = 0,
                            RaidExpansionId = 9
                        },
                        new
                        {
                            Id = 42,
                            ImageUrl = "raids/42.png",
                            Name = "Vault of the Incarnates",
                            RaidDifficulty = 0,
                            RaidExpansionId = 10
                        });
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Avatar")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Member"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Officer"
                        });
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.Character", b =>
                {
                    b.HasOne("GuildManager_DataAccess.Entities.CharacterClass", "Class")
                        .WithMany("Characters")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GuildManager_DataAccess.Entities.ClassSpecialization", "MainSpec")
                        .WithMany("Characters")
                        .HasForeignKey("ClassSpecializationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("GuildManager_DataAccess.Entities.User", "User")
                        .WithMany("Characters")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("MainSpec");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.ClassSpecialization", b =>
                {
                    b.HasOne("GuildManager_DataAccess.Entities.CharacterClass", "CharacterClass")
                        .WithMany("ClassSpecializations")
                        .HasForeignKey("CharacterClassId")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();

                    b.Navigation("CharacterClass");
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.Raids.RaidEvent", b =>
                {
                    b.HasOne("GuildManager_DataAccess.Entities.Raids.RaidLocation", "RaidLocation")
                        .WithMany()
                        .HasForeignKey("RaidLocationId");

                    b.Navigation("RaidLocation");
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.Raids.RaidEventCharacter", b =>
                {
                    b.HasOne("GuildManager_DataAccess.Entities.Character", "Character")
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildManager_DataAccess.Entities.Raids.RaidEvent", "RaidEvent")
                        .WithMany()
                        .HasForeignKey("RaidEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Character");

                    b.Navigation("RaidEvent");
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.Raids.RaidLocation", b =>
                {
                    b.HasOne("GuildManager_DataAccess.Entities.Raids.RaidExpansion", "Expansion")
                        .WithMany()
                        .HasForeignKey("RaidExpansionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GuildManager_DataAccess.Entities.Raids.RaidExpansion", null)
                        .WithMany("Raids")
                        .HasForeignKey("RaidExpansionId1");

                    b.Navigation("Expansion");
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.User", b =>
                {
                    b.HasOne("GuildManager_DataAccess.Entities.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.CharacterClass", b =>
                {
                    b.Navigation("Characters");

                    b.Navigation("ClassSpecializations");
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.ClassSpecialization", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.Raids.RaidExpansion", b =>
                {
                    b.Navigation("Raids");
                });

            modelBuilder.Entity("GuildManager_DataAccess.Entities.User", b =>
                {
                    b.Navigation("Characters");
                });
#pragma warning restore 612, 618
        }
    }
}
